"""
Integration tests: verify that web_url fields generated by the URL decoration layer
(items 46–49) are accessible via HTTP and use the correct URL patterns.

Requires a live Immich instance and a .env_web file (or path in IMMICH_ENV_WEB) with:
    IMMICH_BASE_URL=https://your-immich.example.com
    IMMICH_API_KEY=<api-key-with-read-access>
    IMMICH_EMAIL=<user@example.com>
    IMMICH_PASSWORD=<password>

The email/password are used to obtain a session accessToken via POST /api/auth/login.
That token is then used as a Bearer credential when GET-ing the generated web_url values,
which are frontend SPA routes that require authentication.

Run with:
    pytest tests/test_integration_url_access.py -v

Skip conditions (non-fatal, counted as skipped by pytest):
  - .env_web missing
  - Immich server unreachable (ping fails)
  - Login fails (missing IMMICH_EMAIL / IMMICH_PASSWORD or server rejects credentials)
  - No data of that type exists in the instance (e.g. no albums → test_album_* is skipped)
"""
import os
import random
import re
import unittest

import httpx

from mcp4immich.http_client import _probe, _request
from mcp4immich.http_client import ImmichAPIError
from mcp4immich.tooling import _decorate_response
from mcp4immich.config import get_external_domain

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_DEFAULT_ENV_FILE = ".env_web"


def _parse_env_file(path: str) -> dict[str, str]:
    """Parse a simple KEY=VALUE env file, handling export prefix and quotes."""
    env_vars: dict[str, str] = {}
    with open(path, "r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("export "):
                line = line[len("export "):]
            if "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key:
                env_vars[key] = value
    return env_vars


def _ensure_server_reachable() -> None:
    probe = _probe("GET", "/api/server/ping")
    if not probe.get("ok"):
        detail = probe.get("detail") or probe.get("error") or "unknown error"
        raise unittest.SkipTest(f"Immich server not reachable: {detail}")


def _login(email: str, password: str) -> str:
    """POST /api/auth/login and return accessToken, or raise SkipTest."""
    try:
        response = _request(
            "POST",
            "/api/auth/login",
            json_body={"email": email, "password": password},
        )
    except Exception as exc:
        raise unittest.SkipTest(f"Login request failed: {exc}") from exc
    if not isinstance(response, dict):
        raise unittest.SkipTest("Unexpected login response (not JSON dict)")
    token = response.get("accessToken")
    if not token:
        raise unittest.SkipTest(
            f"Login did not return accessToken. Response keys: {list(response.keys())}"
        )
    return token


# ---------------------------------------------------------------------------
# Test class
# ---------------------------------------------------------------------------

class IntegrationUrlAccessTests(unittest.TestCase):
    """
    Live integration tests that:
      1. Fetch real API responses through the URL decoration layer.
      2. Assert web_url values have the correct URL pattern for each entity type.
      3. HTTP GET each web_url with a session Bearer token to confirm no 404.

    All tests in this class are skipped automatically when the .env_web file is
    absent or the Immich server is unreachable.
    """

    _original_env: dict[str, str] = {}
    _access_token: str | None = None
    _external_domain: str | None = None

    @classmethod
    def setUpClass(cls) -> None:
        cls._original_env = os.environ.copy()

        env_path = os.getenv("IMMICH_ENV_WEB", _DEFAULT_ENV_FILE)
        if not os.path.exists(env_path):
            raise unittest.SkipTest(
                f"Missing env file: {env_path}. "
                "Create it with IMMICH_BASE_URL, IMMICH_API_KEY, "
                "IMMICH_EMAIL, IMMICH_PASSWORD."
            )
        os.environ.update(_parse_env_file(env_path))

        _ensure_server_reachable()

        email = os.getenv("IMMICH_EMAIL", "").strip()
        password = os.getenv("IMMICH_PASSWORD", "").strip()
        if not email or not password:
            raise unittest.SkipTest(
                "IMMICH_EMAIL and IMMICH_PASSWORD must be set in .env_web "
                "to obtain a session token for web URL access."
            )

        cls._access_token = _login(email, password)
        cls._external_domain = get_external_domain()

        if not cls._external_domain:
            raise unittest.SkipTest(
                "Could not determine external domain. "
                "Set IMMICH_EXTERNAL_DOMAIN in .env_web or ensure "
                "/api/server-config returns a non-empty externalDomain."
            )

    @classmethod
    def tearDownClass(cls) -> None:
        os.environ.clear()
        os.environ.update(cls._original_env)

    # ------------------------------------------------------------------
    # Shared assertion helper
    # ------------------------------------------------------------------

    def _assert_web_url_accessible(self, web_url: str) -> None:
        """
        HTTP GET a generated web_url with the session Bearer token and assert
        that the response is not a 404 and not any other 4xx/5xx error.
        """
        self.assertIsNotNone(self._access_token, "No access token available")
        headers = {"Authorization": f"Bearer {self._access_token}"}
        try:
            with httpx.Client(follow_redirects=True, timeout=15) as client:
                response = client.get(web_url, headers=headers)
        except httpx.RequestError as exc:
            self.fail(f"Network error GETting {web_url}: {exc}")

        self.assertNotEqual(
            response.status_code,
            404,
            f"web_url returned 404 (entity not found or wrong URL pattern): {web_url}",
        )
        self.assertLess(
            response.status_code,
            400,
            f"web_url returned HTTP {response.status_code}: {web_url}",
        )

    # ------------------------------------------------------------------
    # Tests
    # ------------------------------------------------------------------

    def test_asset_web_url_accessible(self) -> None:
        """
        GET /api/assets (fallback: POST /api/search/assets) → first item must
        have web_url matching .../photos/{id}.
        The URL must be accessible (not 404).
        """
        items: list[dict[str, object]] = []
        try:
            raw = _request("GET", "/api/assets", params={"take": 1}, require_auth=True)
            items = raw if isinstance(raw, list) else []
        except ImmichAPIError as exc:
            if exc.status_code != 404:
                raise

        # Fallback for Immich versions that don't expose GET /api/assets
        if not items:
            try:
                raw_search = _request(
                    "POST",
                    "/api/search/assets",
                    json_body={"order": "desc", "page": 1, "size": 1},
                    require_auth=True,
                )
            except Exception as exc:
                self.skipTest(f"Could not fetch assets via fallback search: {exc}")

            if isinstance(raw_search, dict):
                assets_wrapper = raw_search.get("assets")
                if isinstance(assets_wrapper, dict):
                    maybe_items = assets_wrapper.get("items")
                    items = maybe_items if isinstance(maybe_items, list) else []

        if not items:
            self.skipTest("No assets available in this Immich instance")

        decorated = _decorate_response(items, self._external_domain, "array")
        first = decorated[0] if isinstance(decorated, list) else decorated

        web_url = first.get("web_url")
        self.assertIsNotNone(web_url, "web_url field missing from decorated asset response")

        asset_id = re.escape(first.get("id", ""))
        self.assertRegex(
            web_url,
            rf".*/photos/{asset_id}$",
            f"Asset web_url has unexpected pattern: {web_url}",
        )

        person_id = first.get("personId")
        if isinstance(person_id, str) and person_id:
            self.assertNotRegex(
                web_url,
                rf".*/photos/{re.escape(person_id)}$",
                f"Asset web_url incorrectly uses person UUID instead of asset UUID: {web_url}",
            )

        self._assert_web_url_accessible(web_url)

    def test_album_web_url_accessible(self) -> None:
        """
        GET /api/albums → first item must have web_url matching .../albums/{id}.
        The URL must be accessible (not 404).
        """
        raw = _request("GET", "/api/albums", require_auth=True)
        items = raw if isinstance(raw, list) else []
        if not items:
            self.skipTest("No albums available in this Immich instance")

        decorated = _decorate_response(items, self._external_domain, "array")
        first = decorated[0] if isinstance(decorated, list) else decorated

        web_url = first.get("web_url")
        self.assertIsNotNone(web_url, "web_url field missing from decorated album response")

        # Albums use their primary id
        album_id = re.escape(first.get("albumId") or first.get("id") or "")
        self.assertRegex(
            web_url,
            rf".*/albums/{album_id}$",
            f"Album web_url has unexpected pattern: {web_url}",
        )

        self._assert_web_url_accessible(web_url)

    def test_person_web_url_accessible(self) -> None:
        """
        GET /api/people → first item must have web_url matching .../people/{id},
        NOT .../photos/{id}.

        This is the live regression test for item 49: person objects decorated
        with /photos/{id} instead of /people/{id} produce 404 responses when
        accessed, because a person's UUID is not a valid asset ID.
        """
        raw = _request("GET", "/api/people", require_auth=True)

        # Immich wraps /api/people in {"people": [...], "hasNextPage": ...}
        if isinstance(raw, dict):
            items = raw.get("people") or []
        else:
            items = raw if isinstance(raw, list) else []

        if not items:
            self.skipTest("No people available in this Immich instance")

        decorated = _decorate_response(raw, self._external_domain, "array")

        # Extract the decorated people list from the (possibly) wrapped response
        if isinstance(decorated, dict):
            people = decorated.get("people") or []
        else:
            people = decorated if isinstance(decorated, list) else []

        if not people:
            self.skipTest("Decorated people list is empty")

        first = people[0]
        web_url = first.get("web_url")
        person_id = first.get("id", "")

        self.assertIsNotNone(web_url, "web_url field missing from decorated person response")

        # Regression check: must NOT be an asset URL (item 49 bug)
        self.assertNotRegex(
            web_url,
            rf".*/photos/{re.escape(person_id)}$",
            f"Person object received asset URL /photos/{{id}} — item 49 regression detected: {web_url}",
        )

        # Positive check: must be the correct person URL
        self.assertRegex(
            web_url,
            rf".*/people/{re.escape(person_id)}$",
            f"Person web_url has unexpected pattern (expected /people/{{id}}): {web_url}",
        )

        self._assert_web_url_accessible(web_url)

    def test_newest_image_search_web_url_accessible(self) -> None:
        """
        POST /api/search/assets with type=IMAGE and order=desc, page=1 →
        the newest image must have a web_url matching .../photos/{id} that is
        accessible (not 404).

        This exercises the full pipeline end-to-end: search endpoint → URL
        decoration of a wrapped search response → live HTTP access of the
        generated web_url.
        """
        search_body = {
            "type": "IMAGE",
            "order": "desc",
            "page": 1,
            "size": 1,
        }
        try:
            raw = _request(
                "POST",
                "/api/search/assets",
                json_body=search_body,
                require_auth=True,
            )
        except Exception as exc:
            self.skipTest(f"Could not search assets: {exc}")

        # Immich search response is wrapped:
        # {"assets": {"items": [...], "nextPage": null, "total": N, "count": N}}
        if isinstance(raw, dict):
            assets_wrapper = raw.get("assets")
            items = (
                assets_wrapper.get("items") or []
                if isinstance(assets_wrapper, dict)
                else []
            )
        else:
            items = raw if isinstance(raw, list) else []

        if not items:
            self.skipTest("Search returned no images")

        decorated_raw = _decorate_response(raw, self._external_domain, "array")

        # Extract decorated items from the wrapped structure
        if isinstance(decorated_raw, dict):
            assets_wrapper_dec = decorated_raw.get("assets")
            decorated_items = (
                assets_wrapper_dec.get("items") or []
                if isinstance(assets_wrapper_dec, dict)
                else []
            )
        else:
            decorated_items = decorated_raw if isinstance(decorated_raw, list) else []

        if not decorated_items:
            self.skipTest("Decorated search response contains no items")

        first = decorated_items[0]
        web_url = first.get("web_url")
        asset_id = re.escape(first.get("id", ""))

        self.assertIsNotNone(
            web_url, "web_url field missing from decorated search result"
        )
        self.assertRegex(
            web_url,
            rf".*/photos/{asset_id}$",
            f"Search result web_url has unexpected pattern: {web_url}",
        )

        self._assert_web_url_accessible(web_url)

    def test_random_person_web_url_accessible(self) -> None:
        """
        GET /api/people → pick a random person → assert web_url matches
        .../people/{id} and is accessible (not 404).
        Skipped if no people exist.
        """
        raw = _request("GET", "/api/people", require_auth=True)

        if isinstance(raw, dict):
            all_people = raw.get("people") or []
        else:
            all_people = raw if isinstance(raw, list) else []

        if not all_people:
            self.skipTest("No people available in this Immich instance")

        chosen = random.choice(all_people)
        decorated = _decorate_response(chosen, self._external_domain, "person")
        if not isinstance(decorated, dict):
            decorated = chosen

        person_id = chosen.get("id", "")
        web_url = decorated.get("web_url")

        self.assertIsNotNone(web_url, f"web_url missing for random person id={person_id}")
        self.assertRegex(
            web_url,
            rf".*/people/{re.escape(person_id)}$",
            f"Random person web_url has unexpected pattern: {web_url}",
        )
        self._assert_web_url_accessible(web_url)

    def test_random_album_web_url_accessible(self) -> None:
        """
        GET /api/albums → pick a random album → assert web_url matches
        .../albums/{id} and is accessible (not 404).
        Skipped if no albums exist.
        """
        raw = _request("GET", "/api/albums", require_auth=True)
        all_albums = raw if isinstance(raw, list) else []

        if not all_albums:
            self.skipTest("No albums available in this Immich instance")

        chosen = random.choice(all_albums)
        decorated = _decorate_response(chosen, self._external_domain, "album")
        if not isinstance(decorated, dict):
            decorated = chosen

        album_id = re.escape(chosen.get("albumId") or chosen.get("id") or "")
        web_url = decorated.get("web_url")

        self.assertIsNotNone(web_url, f"web_url missing for random album id={album_id}")
        self.assertRegex(
            web_url,
            rf".*/albums/{album_id}$",
            f"Random album web_url has unexpected pattern: {web_url}",
        )
        self._assert_web_url_accessible(web_url)

    def test_random_video_web_url_accessible(self) -> None:
        """
        POST /api/search/assets with type=VIDEO → pick a random video from the
        first page → assert web_url matches .../photos/{id} and is accessible
        (not 404). Skipped if no videos exist.
        """
        try:
            raw = _request(
                "POST",
                "/api/search/assets",
                json_body={"type": "VIDEO", "page": 1, "size": 50},
                require_auth=True,
            )
        except Exception as exc:
            self.skipTest(f"Could not search for videos: {exc}")

        if isinstance(raw, dict):
            assets_wrapper = raw.get("assets")
            items = (
                assets_wrapper.get("items") or []
                if isinstance(assets_wrapper, dict)
                else []
            )
        else:
            items = raw if isinstance(raw, list) else []

        if not items:
            self.skipTest("No videos found in this Immich instance")

        chosen = random.choice(items)
        decorated = _decorate_response(chosen, self._external_domain, "asset")
        if not isinstance(decorated, dict):
            decorated = chosen

        asset_id = re.escape(chosen.get("id", ""))
        web_url = decorated.get("web_url")

        self.assertIsNotNone(web_url, f"web_url missing for random video id={asset_id}")
        self.assertRegex(
            web_url,
            rf".*/photos/{asset_id}$",
            f"Random video web_url has unexpected pattern: {web_url}",
        )
        self._assert_web_url_accessible(web_url)

    def test_place_web_url_accessible(self) -> None:
        """
        GET /api/places → first item must have web_url for the explore/places view.
        The URL must be accessible (not 404). Skipped if no places exist.
        """
        try:
            raw = _request("GET", "/api/places", require_auth=True)
        except Exception as exc:
            self.skipTest(f"Could not fetch /api/places: {exc}")

        items = raw if isinstance(raw, list) else []
        if not items:
            self.skipTest("No places available in this Immich instance")

        decorated = _decorate_response(items, self._external_domain, "array")
        first = decorated[0] if isinstance(decorated, list) else decorated

        web_url = first.get("web_url")
        if not web_url:
            # Place items may not always have a web_url if detection failed
            self.skipTest(
                f"web_url missing from first place item (keys: {list(first.keys())})"
            )

        self.assertIn(
            "explore",
            web_url,
            f"Place web_url expected to contain 'explore', got: {web_url}",
        )

        self._assert_web_url_accessible(web_url)
